export const TIME_OFF_REQUEST_STATUS = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  APPROVAL_FAILED: 'APPROVAL_FAILED',
} as const;

export type TimeOffRequestStatus =
  (typeof TIME_OFF_REQUEST_STATUS)[keyof typeof TIME_OFF_REQUEST_STATUS];
